import { CalendarDays, Clock3, Info, LogIn, LogOut, X } from 'lucide-react'
import ReactRuntime from 'react'
import { createPortal } from 'react-dom'
import { dateLabel, durationLabel, minutesBetween } from './attendanceData'
import { ATTENDANCE_LEGEND_STATUSES, attendanceStatusTone } from './attendanceStatus'

globalThis.React = ReactRuntime

export function Modal({title,subtitle,onClose,children,wide=false}){ReactRuntime.useEffect(()=>{const close=event=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose]);const content=<div className="att-modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`att-modal${wide?' is-wide':''}`} role="dialog" aria-modal="true"><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button onClick={onClose} aria-label="Close"><X size={20}/></button></header>{children}</section></div>;return typeof document==='undefined'?content:createPortal(content,document.body)}
export function Toast({toast}){return toast?<div className={`att-toast is-${toast.tone||'success'}`} role="status">{toast.message}</div>:null}
export function StatusPill({status}){return <span className={`att-status is-${attendanceStatusTone(status)}`}>{status}</span>}

export function TodayAttendanceCard({today,clock,onClock,onCorrection,onLeave,disabledReason}){
 // eslint-disable-next-line react-hooks/purity
 const worked=clock.in?(clock.out?minutesBetween(clock.in,clock.out):Math.max(0,Math.floor((Date.now()-clock.timestamp)/60000))):0
 const status=disabledReason||(!clock.in?'Not Clocked In':clock.out?'Clocked Out':'Currently Working')
 return <section className="att-card att-today"><div className="att-today-main"><div className="att-eyebrow"><span>Today’s Attendance</span>{today.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div><div className="att-today-stats"><div><small>Status</small><strong>{status}</strong></div><div><small>Clock In</small><strong>{clock.in||'—'}</strong></div><div><small>Clock Out</small><strong>{clock.out||'—'}</strong></div><div><small>Worked</small><strong>{clock.in?durationLabel(worked):'—'}</strong></div></div>{disabledReason&&<div className="att-info"><Info size={17}/>{disabledReason==='Weekly Off'?'Sundays are weekly off. No attendance action required.':`Attendance is disabled: ${disabledReason}.`}</div>}</div><div className="att-today-actions"><button className="att-primary" disabled={!!disabledReason||!!clock.out} onClick={onClock}>{clock.in?<LogOut size={17}/>:<LogIn size={17}/>} {clock.in?'Clock Out':'Clock In'}</button><div><button className="att-secondary" onClick={onCorrection}>Request Correction</button><button className="att-secondary" onClick={onLeave}>Apply Leave</button></div></div></section>
}

export function AttendanceCalendar({year,month,records,holidays,onMonth,onDay}){
 const first=new Date(year,month,1), count=new Date(year,month+1,0).getDate(), offset=(first.getDay()+6)%7, today=new Date(), cells=Array(offset).fill(null)
 for(let d=1;d<=count;d++){const date=new Date(year,month,d),key=date.toLocaleDateString('en-CA'),holiday=holidays.find(h=>h.date===key),record=records[key];let status=record?.status||holiday&&'Holiday'||date.getDay()===0&&'Weekly Off'||date>today&&'Future'||'Not Marked';cells.push({date,key,status,holiday,record})}
 return <section className="att-card att-calendar"><div className="att-calendar-head"><div><h2>Monthly Calendar</h2><p>Click any date for details.</p></div>{onMonth}</div><div className="att-week"><b>Mon</b><b>Tue</b><b>Wed</b><b>Thu</b><b>Fri</b><b>Sat</b><b>Sun</b>{cells.map((cell,i)=>cell?<button key={cell.key} className={`att-day is-${attendanceStatusTone(cell.status)}${cell.key===today.toLocaleDateString('en-CA')?' is-today':''}`} onClick={()=>onDay(cell)}><strong>{cell.date.getDate()}</strong><span>{cell.status==='Future'?'':cell.status}</span>{cell.record?.in&&<small>{cell.record.in} – {cell.record.out||'…'}</small>}{cell.holiday&&<small>{cell.holiday.name}</small>}</button>:<i key={`blank-${i}`}/>)}</div><div className="att-legend">{ATTENDANCE_LEGEND_STATUSES.map(label=><span key={label}><i className={`is-${attendanceStatusTone(label)}`}/>{label}</span>)}</div></section>
}

export function CorrectionModal({date='',existing,onClose,onSubmit}){const React=globalThis.React;const [form,setForm]=React.useState({date,clockIn:existing?.in||'09:30',clockOut:existing?.out||'18:30',reason:''});const mins=minutesBetween(form.clockIn,form.clockOut),canSubmit=Boolean(form.date&&form.clockIn&&form.clockOut&&mins>0&&form.reason.trim());return <Modal title="Request Attendance Correction" subtitle="Fix a missed clock-in or clock-out. Requires approval." onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(canSubmit)onSubmit(form)}}><div className="att-form"><label>Attendance Date *<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>{existing&&<div className="att-info">Existing: {existing.in||'No clock-in'} — {existing.out||'No clock-out'}</div>}<div className="att-form-grid"><label>Corrected Clock-In *<input type="time" value={form.clockIn} onChange={e=>setForm({...form,clockIn:e.target.value})}/></label><label>Corrected Clock-Out *<input type="time" value={form.clockOut} onChange={e=>setForm({...form,clockOut:e.target.value})}/></label></div><div className="att-duration"><b>Calculated Duration:</b> {durationLabel(mins)}</div><label>Reason for Correction *<textarea rows="4" placeholder="Explain why the correction is needed…" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div><footer><button type="button" className="att-secondary" onClick={onClose}>Cancel</button><button type="submit" className="att-primary" disabled={!canSubmit}>Submit for Approval</button></footer></form></Modal>}

export function DetailsModal({cell,onClose,onCorrection,onLeave}){const leaveMarked=['Leave','Half Day Leave','Leave - Pending Approval','Leave - Rejected'].includes(cell.status),correctionDisabled=['Future','Holiday','Weekly Off','Leave - Pending Approval','Leave - Rejected'].includes(cell.status);return <Modal title={dateLabel(cell.key)} subtitle="Attendance details" onClose={onClose}><div className="att-detail"><CalendarDays size={30}/><StatusPill status={cell.status}/><dl><div><dt>Clock-in</dt><dd>{cell.record?.in||'—'}</dd></div><div><dt>Clock-out</dt><dd>{cell.record?.out||'—'}</dd></div><div><dt>Duration</dt><dd>{cell.record?.duration||'—'}</dd></div>{cell.holiday&&<div><dt>Holiday</dt><dd>{cell.holiday.name}</dd></div>}</dl></div><footer><button className="att-secondary" disabled={correctionDisabled} onClick={onCorrection}><Clock3 size={16}/> Request correction</button><button className="att-primary" disabled={leaveMarked} onClick={onLeave}>Apply leave</button></footer></Modal>}
