import { apiFetch, invalidateApiJsonCache } from './apiClient'
async function request(path,init={}){const response=await apiFetch(`/api/attendance${path}`,{...init,headers:{'Content-Type':'application/json',...(init.headers||{})}}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Attendance request failed.');return payload.data}
const body=value=>({method:'POST',body:JSON.stringify(value||{})})
export const getAttendancePermissions=()=>request('/permissions')
export const updateAttendancePermissions=value=>request('/permissions',{method:'PUT',body:JSON.stringify(value)})
export const getTodayAttendance=()=>request('/today')
export const clockIn=()=>request('/clock-in',body())
export const clockOut=()=>request('/clock-out',body())
export const getMonthlyAttendance=(year,month,userId='')=>request(`/month?year=${year}&month=${month}${userId?`&user_id=${encodeURIComponent(userId)}`:''}`)
export const getLeaveBalance=(financialYear='',asOf='')=>request(`/balance?${financialYear?`financial_year=${encodeURIComponent(financialYear)}`:''}${financialYear&&asOf?'&':''}${asOf?`as_of=${encodeURIComponent(asOf)}`:''}`)
export const previewLeaveRequest=value=>request('/leave/preview',body(value))
export const createLeaveRequest=value=>request('/leave',body(value))
export const getMyLeaveRequests=()=>request('/leave')
export const getLeaveApprovalRequests=()=>request('/leave?approval=true')
export const cancelLeaveRequest=id=>request(`/leave/${id}/cancel`,body())
export const reviewLeaveRequest=(id,decision,note)=>request(`/leave/${id}/review`,body({decision,note}))
export const createCorrectionRequest=value=>request('/corrections',body(value))
export const getMyCorrectionRequests=()=>request('/corrections')
export const getCorrectionApprovalRequests=()=>request('/corrections?approval=true')
export const cancelCorrectionRequest=id=>request(`/corrections/${id}/cancel`,body())
export const reviewCorrectionRequest=(id,decision,note)=>request(`/corrections/${id}/review`,body({decision,note}))
export const getHolidays=(start,end)=>request(`/holidays?start=${start}&end=${end}`)
export const createHoliday=value=>request('/holidays',body(value))
export const deactivateHoliday=id=>request(`/holidays/${id}`,{method:'DELETE'})
export const getTeamAttendanceSummary=(year,month)=>request(`/team?year=${year}&month=${month}`)
export function invalidateAttendance(){invalidateApiJsonCache('/attendance')}
