const express = require('express')
const controller = require('../controllers/adminController')
const employeeController = require('../controllers/employeeManagementController')
const { requireAdmin, requireSuperAdmin } = require('../middleware/adminAccessMiddleware')

const router = express.Router()

router.get('/me', controller.me)
router.route('/dashboard-visibility').get(controller.dashboardVisibility).patch(controller.dashboardVisibility)
router.get('/column-permissions', controller.columnPermissions)
router.route('/page-view-permissions').get(controller.pageViewPermissions).patch(controller.pageViewPermissions)
router.use(requireAdmin)
router.get('/bootstrap', controller.bootstrap)
router.route('/consultant-report-visibility').get(controller.consultantReportVisibility).patch(requireSuperAdmin, controller.consultantReportVisibility)
router.get('/users', controller.users)
router.get('/user-profiles', controller.userProfiles)
router.get('/employees', employeeController.list)
router.get('/employees/:employeeId/reassignment-records', requireSuperAdmin, employeeController.records)
router.get('/employees/:employeeId', employeeController.detail)
router.patch('/employees/:employeeId/status', requireSuperAdmin, employeeController.updateStatus)
router.post('/employees/:employeeId/reassign', requireSuperAdmin, employeeController.reassign)
router.post('/users', controller.addUser)
router.patch('/users/:email/role', controller.updateUserRole)
router.delete('/users/:email', controller.removeUser)
router.patch('/column-permissions', controller.updateColumnPermission)
router.get('/locked-records', controller.lockedRecords)
router.patch('/locks/:table/:id', controller.setLock)

module.exports = router
