const router=require('express').Router(), service=require('../services/attendanceService'), supabase=require('../services/supabaseAdmin')
const wrap=fn=>async(req,res)=>{try{return res.json({data:await fn(req)})}catch(e){console.error('attendance:',e.message);return res.status(e.statusCode||500).json({error:e.statusCode?e.message:'Unable to process the attendance request.'})}}
router.get('/permissions',wrap(()=>service.permissions()))
router.put('/permissions',wrap(req=>service.updatePermissions(req.user,req.body)))
router.get('/today',wrap(req=>service.today(req.user)))
router.post('/clock-in',wrap(req=>service.clockIn(req.user)))
router.post('/clock-out',wrap(req=>service.clockOut(req.user)))
router.get('/month',wrap(req=>service.monthly(req.user,req.query.user_id,Number(req.query.year),Number(req.query.month))))
router.get('/balance',wrap(req=>service.leaveBalanceSummary(req.user.id,req.query.financial_year,req.query.as_of)))
router.post('/leave/preview',wrap(req=>service.previewLeave(req.user,req.body)))
router.post('/leave',wrap(req=>service.createLeave(req.user,req.body)))
router.get('/leave',wrap(req=>service.listRequests(req.user,'leave',req.query.approval==='true')))
router.post('/leave/:id/cancel',wrap(req=>service.cancel(req.user,'leave',req.params.id)))
router.post('/leave/:id/review',wrap(req=>service.review(req.user,'leave',req.params.id,req.body.decision,req.body.note)))
router.post('/corrections',wrap(req=>service.createCorrection(req.user,req.body)))
router.get('/corrections',wrap(req=>service.listRequests(req.user,'correction',req.query.approval==='true')))
router.post('/corrections/:id/cancel',wrap(req=>service.cancel(req.user,'correction',req.params.id)))
router.post('/corrections/:id/review',wrap(req=>service.review(req.user,'correction',req.params.id,req.body.decision,req.body.note)))
router.get('/holidays',wrap(req=>service.holidays(req.query.start||'1900-01-01',req.query.end||'2999-12-31',true)))
router.post('/holidays',wrap(async req=>{await service.requirePermission(req.user,'attendance_manage_holidays');const b=req.body;if(!String(b.holiday_name||'').trim())throw Object.assign(new Error('Holiday name is required.'),{statusCode:400});const conflict=await supabase.from('attendance_records').select('id').eq('attendance_date',b.holiday_date).limit(1);if(conflict.data?.length)throw Object.assign(new Error('Attendance already exists for this date.'),{statusCode:409});const {data,error}=await supabase.from('company_holidays').insert({...b,created_by:req.user.id}).select().single();if(error?.code==='23505')throw Object.assign(new Error('An active holiday already exists for this date.'),{statusCode:409});if(error)throw error;return data}))
router.put('/holidays/:id',wrap(async req=>{await service.requirePermission(req.user,'attendance_manage_holidays');const {data,error}=await supabase.from('company_holidays').update({...req.body,updated_by:req.user.id,updated_at:new Date().toISOString()}).eq('id',req.params.id).select().single();if(error)throw error;return data}))
router.delete('/holidays/:id',wrap(async req=>{await service.requirePermission(req.user,'attendance_manage_holidays');const {data,error}=await supabase.from('company_holidays').update({is_active:false,updated_by:req.user.id,updated_at:new Date().toISOString()}).eq('id',req.params.id).select().single();if(error)throw error;return data}))
router.get('/team',wrap(async req=>{await service.requirePermission(req.user,'attendance_view_all');const {data,error}=await supabase.from('user_profiles').select('user_id,name,email');if(error)throw error;return Promise.all((data||[]).map(async p=>({user:p,summary:(await service.monthly(req.user,p.user_id,Number(req.query.year),Number(req.query.month))).kpis,leave_balance:await service.leaveBalanceSummary(p.user_id,req.query.financial_year)}))) }))
module.exports=router
