import { useEffect, useState } from 'react'
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Search, Users } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { useAdminAccess } from '../hooks/useAdminAccess'
import { AttendanceCalendar, CorrectionModal, DetailsModal, Modal, StatusPill, Toast, TodayAttendanceCard } from '../features/attendance/AttendanceComponents'
import { HOLIDAY_TYPES, MONTHS, dateLabel, durationLabel, initials, iso } from '../features/attendance/attendanceData'
import AttendancePermissionSettings from '../features/attendance/AttendancePermissionSettings'
import * as attendanceApi from '../services/attendanceApi'
import './AttendancePage.css'

const now=new Date()
const financialYearForDate=date=>{const year=date.getFullYear(),start=date.getMonth()>=3?year:year-1;return `FY ${start}-${String((start+1)%100).padStart(2,'0')}`}
const financialYearMonths=value=>{const start=Number(value.slice(3,7));return Array.from({length:12},(_,index)=>{const date=new Date(start,3+index,1);return {year:date.getFullYear(),month:date.getMonth(),label:`${MONTHS[date.getMonth()]} ${date.getFullYear()}`}})}
const time=value=>value?new Date(value).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false}):null
const statusLabel=value=>({clocked_in:'Clocked In',present:'Present',on_leave:'Leave',half_day_leave:'Half Day Leave',correction_pending:'Pending Correction',corrected:'Corrected',not_marked:'Not Marked',absent:'Absent'}[value]||value)
const mapCorrection=(x,employee='Team Member')=>({id:x.id,employee:x.employee_name||employee,submitted:x.created_at?.slice(0,10),date:x.attendance_date,clockIn:time(x.requested_clock_in_at),clockOut:time(x.requested_clock_out_at),duration:durationLabel(x.requested_worked_minutes),reason:x.reason,status:statusLabel(x.status==='pending'?'Pending Review':x.status[0].toUpperCase()+x.status.slice(1)),reviewedBy:x.reviewed_by||'—',reviewedOn:x.reviewed_at?.slice(0,10)||'—',note:x.review_note||'—'})
const mapLeave=(x,employee='Team Member')=>({id:x.id,employee:x.employee_name||employee,submitted:x.created_at?.slice(0,10),start:x.start_date,end:x.end_date,type:x.duration_type==='half_day'?`Half Day · ${x.half_day_session}`:'Full Day',charged:Number(x.charged_leave_days),balance:Number(x.balance_before),projected:Number(x.projected_balance),lop:Number(x.loss_of_pay_days),reason:x.reason,status:x.status==='pending'?'Pending Review':x.status[0].toUpperCase()+x.status.slice(1),reviewedBy:x.reviewed_by||'—',reviewedOn:x.reviewed_at?.slice(0,10)||'—',note:x.review_note||'—'})

export default function AttendancePage(){
 const [searchParams]=useSearchParams(), deepTab=searchParams.get('tab')
 const {isAdmin,isSuperAdmin}=useAdminAccess({loadPermissions:false})
 const [tab,setTab]=useState(deepTab==='approval'?'approvals':deepTab==='requests'?'requests':'attendance'),[month,setMonth]=useState(now.getMonth()),[year,setYear]=useState(now.getFullYear()),[financialYear,setFinancialYear]=useState(()=>financialYearForDate(now)),[clock,setClock]=useState({}),[records,setRecords]=useState({}),[corrections,setCorrections]=useState([]),[leaves,setLeaves]=useState([]),[holidays,setHolidays]=useState([]),[summary,setSummary]=useState(null),[leaveSummary,setLeaveSummary]=useState(null),[attendancePermissions,setAttendancePermissions]=useState(null),[modal,setModal]=useState(null),[toast,setToast]=useState(null),[,setTick]=useState(0)
 const admin=isAdmin||isSuperAdmin
 const tell=(message,tone='success')=>setToast({message,tone})
 const hasAttendancePermission=key=>Boolean(isSuperAdmin||attendancePermissions?.[key]==='admins')
 useEffect(()=>{if(!admin)return;attendanceApi.getAttendancePermissions().then(setAttendancePermissions).catch(error=>console.warn('[Attendance] Permissions unavailable',error))},[admin])
 useEffect(()=>{if(isSuperAdmin)Promise.resolve().then(()=>setTab('approvals'))},[isSuperAdmin])
 const refresh=async()=>{
  try {
   const [todayData,monthData,myCorrections,myLeaves,holidayRows,approvalCorrections,approvalLeaves]=await Promise.all([isSuperAdmin?null:attendanceApi.getTodayAttendance(),isSuperAdmin?null:attendanceApi.getMonthlyAttendance(year,month+1),isSuperAdmin?[]:attendanceApi.getMyCorrectionRequests(),isSuperAdmin?[]:attendanceApi.getMyLeaveRequests(),attendanceApi.getHolidays(`${year}-01-01`,`${year}-12-31`),hasAttendancePermission('attendance_approve_corrections')?attendanceApi.getCorrectionApprovalRequests():[],hasAttendancePermission('attendance_approve_leave')?attendanceApi.getLeaveApprovalRequests():[]])
   const balanceData=isSuperAdmin?null:await attendanceApi.getLeaveBalance(financialYear).catch(error=>{console.warn('[Attendance] Leave balance unavailable. Apply the financial-year migration if needed.',error);return null})
   setClock(todayData?{in:time(todayData.clock_in_at),out:time(todayData.clock_out_at),timestamp:new Date(todayData.clock_in_at).getTime()}:{})
   setRecords(Object.fromEntries((monthData?.records||[]).map(r=>[r.attendance_date,{status:statusLabel(r.status),in:time(r.clock_in_at),out:time(r.clock_out_at),duration:durationLabel(r.worked_minutes||0)}])))
   setSummary(monthData?.kpis||null)
   setLeaveSummary(balanceData)
   setCorrections(Object.assign([...myCorrections.map(row=>mapCorrection(row,'Team Member')),...approvalCorrections.map(row=>mapCorrection(row,'Employee'))],{canApprove:hasAttendancePermission('attendance_approve_corrections')}))
   setLeaves(Object.assign([...myLeaves.map(row=>mapLeave(row,'Team Member')),...approvalLeaves.map(row=>mapLeave(row,'Employee'))],{canApprove:hasAttendancePermission('attendance_approve_leave')}))
   setHolidays(holidayRows.map(h=>({id:h.id,name:h.holiday_name,date:h.holiday_date,type:h.holiday_type[0].toUpperCase()+h.holiday_type.slice(1)+' Holiday',description:h.description||''})))
  } catch(err) { tell(err.message,'error') }
 }
 useEffect(()=>{if(!admin||attendancePermissions)Promise.resolve().then(refresh)},[year,month,financialYear,attendancePermissions,admin]) // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!clock.in||clock.out)return;const id=setInterval(()=>setTick(x=>x+1),30000);return()=>clearInterval(id)},[clock])
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),3000);return()=>clearTimeout(id)},[toast])
 const todayKey=iso(now),todayHoliday=holidays.find(h=>h.date===todayKey),disabledReason=now.getDay()===0?'Weekly Off':todayHoliday?.name
 const kpis=[['Working Days',summary?.working_days||0],['Present',summary?.present||0],['Leave',summary?.leave||0],['Corrections',summary?.corrections||0],['Unmarked',summary?.unmarked||0],['Holidays',summary?.holidays||0],['Total Hours',durationLabel(summary?.total_minutes||0)]]
 const moveMonth=delta=>{const d=new Date(year,month+delta,1);setMonth(d.getMonth());setYear(d.getFullYear());setFinancialYear(financialYearForDate(d))}
 const selectFinancialYear=value=>{setFinancialYear(value);const first=financialYearMonths(value)[0];setYear(first.year);setMonth(first.month)}
 const monthControls=<div className="att-month-controls"><button onClick={()=>moveMonth(-1)} aria-label="Previous month"><ChevronLeft/></button><select value={financialYear} onChange={e=>selectFinancialYear(e.target.value)}>{['FY 2025-26','FY 2026-27','FY 2027-28'].map(value=><option key={value}>{value}</option>)}</select><select value={`${year}-${month}`} onChange={e=>{const [nextYear,nextMonth]=e.target.value.split('-').map(Number);setYear(nextYear);setMonth(nextMonth)}}>{financialYearMonths(financialYear).map(item=><option value={`${item.year}-${item.month}`} key={item.label}>{item.label}</option>)}</select><button onClick={()=>moveMonth(1)} aria-label="Next month"><ChevronRight/></button><button className="is-current" onClick={()=>{setFinancialYear(financialYearForDate(now));setMonth(now.getMonth());setYear(now.getFullYear())}}>Current month</button></div>
 const openCorrection=(key=todayKey,record=records[key])=>setModal({type:'correction',key,record})
 const submitCorrection=async form=>{try{const offset=-new Date().getTimezoneOffset(),sign=offset>=0?'+':'-',oh=String(Math.floor(Math.abs(offset)/60)).padStart(2,'0'),om=String(Math.abs(offset)%60).padStart(2,'0'),zone=`${sign}${oh}:${om}`;await attendanceApi.createCorrectionRequest({attendance_date:form.date,requested_clock_in_at:`${form.date}T${form.clockIn}:00${zone}`,requested_clock_out_at:`${form.date}T${form.clockOut}:00${zone}`,reason:form.reason});setModal(null);await refresh();tell('Correction request submitted for approval.')}catch(err){tell(err.message,'error')}}
 const onClock=async()=>{try{if(!clock.in)await attendanceApi.clockIn();else await attendanceApi.clockOut();await refresh();tell(clock.in?'Clocked out successfully.':'Clocked in successfully.')}catch(err){tell(err.message,'error')}}
 const tabs=[...(isSuperAdmin?[]:[['attendance','My Attendance',CalendarDays],['requests','My Requests',ClipboardList]]),...((hasAttendancePermission('attendance_approve_corrections')||hasAttendancePermission('attendance_approve_leave'))?[['approvals','Approval Centre',CheckCircle2]]:[]),...(hasAttendancePermission('attendance_manage_holidays')?[['holidays','Holiday Calendar',CalendarDays]]:[]),...(hasAttendancePermission('attendance_view_all')?[['team','Team Attendance',Users]]:[]),...(hasAttendancePermission('attendance_manage_leave_balances')?[['leave-balances','Leave Balance',ClipboardList]]:[])]
 return <div className="attendance-page"><Toast toast={toast}/><header className="att-page-head"><h1>Attendance &amp; Leave</h1><p>Track attendance, manage leave and review monthly attendance records.</p></header><nav className="att-tabs">{tabs.map(([key,label,Icon])=><button className={tab===key?'is-active':''} key={key} onClick={()=>setTab(key)}><Icon size={17}/>{label}{key==='approvals'&&<em>{corrections.filter(x=>x.status==='Pending Review').length+leaves.filter(x=>x.status==='Pending Review').length}</em>}</button>)}</nav>
 {tab==='attendance'&&<><TodayAttendanceCard today={now} clock={clock} onClock={onClock} onCorrection={()=>openCorrection()} onLeave={()=>setModal({type:'leave'})} disabledReason={disabledReason}/><section className="att-card att-leave-summary"><div><span>Available Leave Balance</span><strong className={Number(leaveSummary?.available_balance)<0?'danger':''}>{leaveSummary?.available_balance??'—'} {leaveSummary?.available_balance===1?'day':'days'}</strong></div></section><div className="att-kpis">{kpis.map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><AttendanceCalendar year={year} month={month} records={records} holidays={holidays} onMonth={monthControls} onDay={cell=>setModal({type:'details',cell})}/></>}
 {tab==='requests'&&<Requests corrections={corrections.filter(x=>x.employee==='Team Member')} leaves={leaves.filter(x=>x.employee==='Team Member')} onCancel={async(kind,id)=>{try{await (kind==='correction'?attendanceApi.cancelCorrectionRequest(id):attendanceApi.cancelLeaveRequest(id));await refresh();tell('Request cancelled.')}catch(err){tell(err.message,'error')}}}/>} 
 {tab==='approvals'&&admin&&<Approvals corrections={corrections} leaves={leaves} onReview={(kind,item)=>setModal({type:'review',kind,item})}/>} {tab==='holidays'&&<Holidays admin={admin} year={year} setYear={setYear} holidays={holidays} onAdd={()=>setModal({type:'holiday'})} onDelete={async id=>{try{await attendanceApi.deactivateHoliday(id);await refresh();tell('Holiday removed.')}catch(err){tell(err.message,'error')}}}/>} {tab==='team'&&admin&&<Team year={year} month={month} setYear={setYear} setMonth={setMonth}/>} 
 {modal?.type==='correction'&&<CorrectionModal date={modal.key} existing={modal.record} onClose={()=>setModal(null)} onSubmit={submitCorrection}/>} {modal?.type==='details'&&<DetailsModal cell={modal.cell} onClose={()=>setModal(null)} onCorrection={()=>{const c=modal.cell;setModal({type:'correction',key:c.key,record:c.record})}} onLeave={()=>setModal({type:'leave',date:modal.cell.key})}/>} {modal?.type==='leave'&&<LeaveModal date={modal.date} holidays={holidays} onClose={()=>setModal(null)} onSubmit={async item=>{try{await attendanceApi.createLeaveRequest({start_date:item.start,end_date:item.end,duration_type:item.type.startsWith('Half Day')?'half_day':'full_day',half_day_session:item.type.includes('Second')?'second_half':'first_half',reason:item.reason});setModal(null);await refresh();tell('Leave request submitted for approval.')}catch(err){tell(err.message,'error')}}}/>} {modal?.type==='review'&&<ReviewModal {...modal} onClose={()=>setModal(null)} onSubmit={async(status,note)=>{try{await (modal.kind==='correction'?attendanceApi.reviewCorrectionRequest(modal.item.id,status.toLowerCase(),note):attendanceApi.reviewLeaveRequest(modal.item.id,status.toLowerCase(),note));setModal(null);await refresh();tell(`Request ${status.toLowerCase()}.`)}catch(err){tell(err.message,'error')}}}/>} {modal?.type==='holiday'&&<HolidayForm holidays={holidays} onClose={()=>setModal(null)} onSubmit={async h=>{try{await attendanceApi.createHoliday({holiday_name:h.name,holiday_date:h.date,holiday_type:h.type.split(' ')[0].toLowerCase(),description:h.description});setModal(null);await refresh();tell('Holiday added.')}catch(err){tell(err.message,'error')}}}/>} 
 {tab==='leave-balances'&&hasAttendancePermission('attendance_manage_leave_balances')&&<LeaveBalances financialYear={financialYear}/>}</div>
}

function Requests({corrections,leaves,onCancel}){const [sub,setSub]=useState('correction'),rows=sub==='correction'?corrections:leaves;return <section><SubTabs sub={sub} setSub={setSub}/><Table rows={rows} kind={sub} mine onCancel={onCancel}/></section>}
function Approvals({corrections,leaves,onReview}){const allowCorrections=corrections.canApprove!==false,allowLeave=leaves.canApprove!==false,[sub,setSub]=useState(allowCorrections?'correction':'leave'),active=allowCorrections&&sub==='correction'?'correction':'leave',rows=(active==='correction'?corrections:leaves).filter(x=>x.status==='Pending Review');return <section><SubTabs sub={active} setSub={setSub} counts={[corrections.filter(x=>x.status==='Pending Review').length,leaves.filter(x=>x.status==='Pending Review').length]} allowCorrections={allowCorrections} allowLeave={allowLeave}/><Table rows={rows} kind={active} onReview={onReview}/></section>}
function SubTabs({sub,setSub,counts,allowCorrections=true,allowLeave=true}){return <div className="att-subtabs">{allowCorrections&&<button className={sub==='correction'?'is-active':''} onClick={()=>setSub('correction')}>Attendance Corrections {counts&&<em>{counts[0]}</em>}</button>}{allowLeave&&<button className={sub==='leave'?'is-active':''} onClick={()=>setSub('leave')}>Leave Requests {counts&&<em>{counts[1]}</em>}</button>}</div>}
function Table({rows,kind,mine,onCancel,onReview}){if(!rows.length)return <div className="att-empty"><ClipboardList size={36}/><h3>No {kind==='correction'?'correction':'leave'} requests {mine?'yet':'to review'}.</h3><p>{mine?'New requests will appear here.':'You are all caught up.'}</p></div>;return <div className="att-table-card"><table><thead><tr>{!mine&&<th>Employee</th>}<th>Submitted On</th><th>{kind==='correction'?'Attendance Date':'Leave Period'}</th><th>{kind==='correction'?'Requested Times':'Type'}</th><th>{kind==='correction'?'Duration':'Charged Days'}</th><th>Reason</th><th>Status</th>{mine&&<><th>Reviewed By</th><th>Reviewed On</th><th>Review Note</th></>}<th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}>{!mine&&<td><b>{x.employee}</b></td>}<td>{dateLabel(x.submitted)}</td><td>{kind==='correction'?dateLabel(x.date):`${dateLabel(x.start)} – ${dateLabel(x.end)}`}</td><td>{kind==='correction'?`${x.clockIn} – ${x.clockOut}`:x.type}</td><td>{kind==='correction'?x.duration:x.charged}</td><td className="att-reason">{x.reason}</td><td><StatusPill status={x.status}/></td>{mine&&<><td>{x.reviewedBy}</td><td>{x.reviewedOn}</td><td>{x.note}</td></>}<td>{x.status==='Pending Review'&&(mine?<button className="att-link danger" onClick={()=>onCancel(kind,x.id)}>Cancel</button>:<button className="att-link" onClick={()=>onReview(kind,x)}>Review</button>)}</td></tr>)}</tbody></table></div>}

function LeaveModal({date='',onClose,onSubmit}) {
 const [form,setForm]=useState({start:date,end:date,type:'Full Day',session:'First Half',reason:''})
 const [preview,setPreview]=useState({charged_leave_days:0,balance_before:0,projected_balance:0,loss_of_pay_days:0,calculation_breakdown:[]})
 const [previewing,setPreviewing]=useState(false)
 useEffect(()=>{if(!form.start||!form.end||form.end<form.start)return;let active=true;Promise.resolve().then(()=>{if(active)setPreviewing(true)});const timer=setTimeout(()=>attendanceApi.previewLeaveRequest({start_date:form.start,end_date:form.end,duration_type:form.type==='Half Day'?'half_day':'full_day',half_day_session:form.type==='Half Day'?(form.session==='Second Half'?'second_half':'first_half'):null}).then(value=>{if(active)setPreview(value)}).catch(()=>{if(active)setPreview({charged_leave_days:0,balance_before:0,projected_balance:0,loss_of_pay_days:0,calculation_breakdown:[]})}).finally(()=>{if(active)setPreviewing(false)}),250);return()=>{active=false;clearTimeout(timer)}},[form.start,form.end,form.type,form.session])
 const submit=()=>{if(!form.start||!form.end||form.end<form.start||!form.reason.trim())return;onSubmit({...form,type:form.type==='Half Day'?`${form.type} · ${form.session}`:form.type})}
 return <Modal title="Apply Leave" subtitle="Plan time off and review the leave calculation before submitting." onClose={onClose} wide><div className="att-form"><div className="att-form-grid"><label>Start Date *<input type="date" value={form.start} onChange={e=>setForm({...form,start:e.target.value,end:form.end||e.target.value})}/></label><label>End Date *<input type="date" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label><label>Leave Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Full Day</option><option>Half Day</option></select></label>{form.type==='Half Day'&&<label>Half Day Session<select value={form.session} onChange={e=>setForm({...form,session:e.target.value})}><option>First Half</option><option>Second Half</option></select></label>}</div><div className="att-balance">{[['Available Leave Balance',preview.balance_before],['Requested Leave Days',preview.charged_leave_days],['Projected Balance',preview.projected_balance],['Estimated Loss of Pay',preview.loss_of_pay_days]].map(([label,value])=><div key={label}><small>{label}</small><b className={label==='Projected Balance'&&Number(value)<0?'danger':''}>{previewing?'…':value??'—'}</b></div>)}</div><div className="att-breakdown"><h3>Leave calculation breakdown</h3>{preview.calculation_breakdown.map(d=><div key={d.date}><span>{dateLabel(d.date)}</span><span>{d.reason}</span><b>{d.charged}</b></div>)}</div>{preview.projected_balance<0&&<div className="att-warning"><b>Insufficient Paid Leave Balance</b><span>This request will reduce your paid leave balance below zero. The excess leave may be treated as Loss of Pay according to company policy.</span><span>Current: {preview.balance_before} · Requested: {preview.charged_leave_days} · Projected: {preview.projected_balance} · Estimated LOP: {preview.loss_of_pay_days}</span></div>}<label>Reason *<textarea rows="3" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div><footer><button className="att-secondary" onClick={onClose}>Go Back</button><button className="att-primary" disabled={previewing||!form.start||!form.end||form.end<form.start||!form.reason.trim()} onClick={submit}>{preview.projected_balance<0?'Continue and Submit':'Submit for Approval'}</button></footer></Modal>
}
function ReviewModal({item,kind,onClose,onSubmit}){const [decision,setDecision]=useState('Approved'),[note,setNote]=useState('');return <Modal title="Review Request" subtitle={`${item.employee} · ${kind==='correction'?'Attendance correction':'Leave request'}`} onClose={onClose}><div className="att-review-summary"><StatusPill status={item.status}/><p>{item.reason}</p></div><div className="att-form"><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option>Approved</option><option>Rejected</option></select></label><label>{decision==='Rejected'?'Rejection reason *':'Approval note (optional)'}<textarea rows="4" value={note} onChange={e=>setNote(e.target.value)}/></label></div><footer><button className="att-secondary" onClick={onClose}>Cancel</button><button className="att-primary" disabled={decision==='Rejected'&&!note.trim()} onClick={()=>onSubmit(decision,note)}>{decision==='Approved'?'Approve Request':'Reject Request'}</button></footer></Modal>}
function Holidays({admin,year,setYear,holidays,onAdd,onDelete}){const list=holidays.filter(h=>new Date(`${h.date}T12:00:00`).getFullYear()===year).sort((a,b)=>a.date.localeCompare(b.date));return <section className="att-card att-holidays"><div className="att-section-head"><div><h2>Holiday Calendar</h2><p>Company holidays and optional days off.</p></div><div><select value={year} onChange={e=>setYear(+e.target.value)}><option>2025</option><option>2026</option><option>2027</option></select>{admin&&<button className="att-primary" onClick={onAdd}>+ Add Holiday</button>}</div></div><div className="att-holiday-grid">{list.map(h=><article key={h.id}><div className="att-holiday-date"><b>{new Date(`${h.date}T12:00:00`).getDate()}</b><span>{MONTHS[new Date(`${h.date}T12:00:00`).getMonth()].slice(0,3)}</span></div><div><h3>{h.name}</h3><p>{h.description}</p><StatusPill status={h.type}/></div>{admin&&<button className="att-link danger" onClick={()=>onDelete(h.id)}>Delete</button>}</article>)}</div></section>}
function HolidayForm({holidays,onClose,onSubmit}){const [form,setForm]=useState({name:'',date:'',type:HOLIDAY_TYPES[0],description:''});return <Modal title="Add Holiday" subtitle="Add a day to the company holiday calendar." onClose={onClose}><div className="att-form"><label>Holiday Name *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Date *<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{HOLIDAY_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button className="att-secondary" onClick={onClose}>Cancel</button><button className="att-primary" disabled={!form.name||!form.date||holidays.some(h=>h.date===form.date)} onClick={()=>onSubmit({...form,id:crypto.randomUUID()})}>Add Holiday</button></footer></Modal>}
// eslint-disable-next-line no-unused-vars
function LeaveBalancesLegacy({financialYear}) {
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const load=()=>{setLoading(true);attendanceApi.getLeaveBalances(financialYear).then(setRows).catch(err=>setError(err.message)).finally(()=>setLoading(false))}
 useEffect(()=>{Promise.resolve().then(load)},[financialYear]) // eslint-disable-line react-hooks/exhaustive-deps
 const save=async()=>{if(!selected||!amount)return;setSaving(true);setError('');try{await attendanceApi.adjustLeaveBalance(selected.user.user_id,amount,description,financialYear);setSelected(null);setAmount('');setDescription('');load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <section className="att-card att-holidays"><div className="att-section-head"><div><h2>Leave Balance</h2></div></div>{error&&<div className="att-toast is-error">{error}</div>}{loading?<div className="att-empty"><p>Loading leave balances…</p></div>:<div className="att-table-card"><table><thead><tr><th>Employee</th><th>Available Balance</th><th>Used</th><th>Pending</th><th>LOP Exposure</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.user.user_id}><td><b>{row.user.name||row.user.email}</b><small>{row.user.email}</small></td><td>{row.balance.available_balance} days</td><td>{row.balance.used_leave} days</td><td>{row.balance.pending_leave} days</td><td>{row.balance.loss_of_pay_exposure} days</td><td><button className="att-link" type="button" onClick={()=>setSelected(row)}>Adjust</button></td></tr>)}</tbody></table></div>}{selected&&<Modal title={`Adjust Leave Balance · ${selected.user.name||selected.user.email}`} subtitle={financialYear} onClose={()=>setSelected(null)}><div className="att-form"><label>Adjustment (+/- days)<input type="number" step="0.5" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. 1.5 or -0.5"/></label><label>Description<textarea rows="3" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Reason for adjustment"/></label></div><footer><button className="att-secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="att-primary" disabled={saving||!amount||Number(amount)===0} onClick={save}>{saving?'Saving…':'Save Adjustment'}</button></footer></Modal>}</section>
}

// eslint-disable-next-line no-unused-vars
function AttendanceTableSkeleton({columns=6,rows=7}){return <div className="att-table-card att-loading-table"><table><thead><tr>{Array.from({length:columns},(_,index)=><th key={index}><span className="att-skeleton att-skeleton-head"/></th>)}</tr></thead><tbody>{Array.from({length:rows},(_,row)=><tr key={row}>{Array.from({length:columns},(_,column)=><td key={column}><span className="att-skeleton"/></td>)}</tr>)}</tbody></table></div>}

function LeaveBalances({financialYear}) {
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const load=()=>{setLoading(true);attendanceApi.getLeaveBalances(financialYear).then(setRows).catch(err=>setError(err.message)).finally(()=>setLoading(false))}
 useEffect(()=>{Promise.resolve().then(load)},[financialYear]) // eslint-disable-line react-hooks/exhaustive-deps
 const save=async()=>{if(!selected||!amount)return;setSaving(true);setError('');try{await attendanceApi.adjustLeaveBalance(selected.user.user_id,amount,description,financialYear);setSelected(null);setAmount('');setDescription('');load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <section className="att-card att-holidays"><div className="att-section-head"><div><h2>Leave Balance</h2></div></div>{error&&<div className="att-toast is-error">{error}</div>}{loading?<AttendanceTableSkeleton columns={6}/>:<div className="att-table-card"><table><thead><tr><th>Employee</th><th>Available Balance</th><th>Used</th><th>Pending</th><th>LOP Exposure</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.user.user_id}><td><b>{row.user.name||'Employee'}</b></td><td>{row.balance.available_balance} days</td><td>{row.balance.used_leave} days</td><td>{row.balance.pending_leave} days</td><td>{row.balance.loss_of_pay_exposure} days</td><td><button className="att-link" type="button" onClick={()=>setSelected(row)}>Adjust</button></td></tr>)}</tbody></table></div>}{selected&&<Modal title={`Adjust Leave Balance · ${selected.user.name||'Employee'}`} subtitle={financialYear} onClose={()=>setSelected(null)}><div className="att-form"><label>Adjustment (+/- days)<input type="number" step="0.5" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. 1.5 or -0.5"/></label><label>Description<textarea rows="3" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Reason for adjustment"/></label></div><footer><button className="att-secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="att-primary" disabled={saving||!amount||Number(amount)===0} onClick={save}>{saving?'Saving…':'Save Adjustment'}</button></footer></Modal>}</section>
}

// eslint-disable-next-line no-unused-vars
function TeamLegacy({year,month,setYear,setMonth}) {
 const [query,setQuery]=useState(''),[employee,setEmployee]=useState('all'),[status,setStatus]=useState('all'),[teamRows,setTeamRows]=useState([]),[loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;Promise.resolve().then(()=>{if(active)setLoading(true)});attendanceApi.getTeamAttendanceSummary(year,month+1).then(data=>{if(active)setTeamRows(data||[])}).catch(()=>{if(active)setTeamRows([])}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[year,month])
 const employees=teamRows.map(row=>{const s=row.summary||{},working=s.working_days||0,present=s.present||0;return{id:row.user.user_id,name:row.user.name||row.user.email||'Employee',role:row.user.email||'',working,present,leave:s.leave||0,corrections:s.corrections||0,unmarked:s.unmarked||0,hours:durationLabel(s.total_minutes||0)}})
 const rows=employees.filter(e=>(employee==='all'||e.id===employee)&&(!query||e.name.toLowerCase().includes(query.toLowerCase()))).filter(e=>status==='all'||(status==='low'?(e.working?e.present/e.working:0)<.8:(e.working?e.present/e.working:0)>=.8))
 return <section><div className="att-card att-team-filters"><label><span>Search Employees</span><div><Search size={16}/><input placeholder="Search by name…" value={query} onChange={e=>setQuery(e.target.value)}/></div></label><label>Employee<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">All Employees</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Month<select value={month} onChange={e=>setMonth(+e.target.value)}>{MONTHS.map((m,i)=><option value={i} key={m}>{m}</option>)}</select></label><label>Year<select value={year} onChange={e=>setYear(+e.target.value)}><option>2026</option><option>2025</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All</option><option value="good">80%+</option><option value="low">Below 80%</option></select></label></div>{loading?<div className="att-empty"><p>Loading team attendance…</p></div>:rows.length?<div className="att-table-card"><table><thead><tr><th>Employee</th><th>Working</th><th>Present</th><th>Leave</th><th>Corrections</th><th>Unmarked</th><th>Total Hours</th><th>Attendance %</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><div className="att-person"><i>{initials(e.name)}</i><span><b>{e.name}</b><small>{e.role}</small></span></div></td><td>{e.working}</td><td>{e.present}</td><td>{e.leave}</td><td>{e.corrections}</td><td>{e.unmarked}</td><td>{e.hours}</td><td><StatusPill status={`${e.working?Math.round(e.present/e.working*100):0}%`}/></td></tr>)}</tbody></table></div>:<div className="att-empty"><Users size={36}/><h3>No attendance data found.</h3><p>Employees will appear here when profile data is available.</p></div>}</section>
}

function Team({year,month,setYear,setMonth}) {
 const [query,setQuery]=useState(''),[employee,setEmployee]=useState('all'),[status,setStatus]=useState('all'),[teamRows,setTeamRows]=useState([]),[loading,setLoading]=useState(true),[detail,setDetail]=useState(null)
 const fy=financialYearForDate(new Date(year,month,1))
 useEffect(()=>{let active=true;Promise.resolve().then(()=>{if(active)setLoading(true)});attendanceApi.getTeamAttendanceSummary(year,month+1,fy).then(data=>{if(active)setTeamRows(data||[])}).catch(()=>{if(active)setTeamRows([])}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[year,month,fy])
 const employees=teamRows.map(row=>{const s=row.summary||{},b=row.leave_balance||{};return{id:row.user.user_id,name:row.user.name||row.user.email||'Employee',role:row.user.email||'',working:s.working_days||0,present:s.present||0,leave:s.leave||0,corrections:s.corrections||0,unmarked:s.unmarked||0,hours:durationLabel(s.total_minutes||0),balance:b.available_balance??0}})
 const rows=employees.filter(e=>(employee==='all'||e.id===employee)&&(!query||e.name.toLowerCase().includes(query.toLowerCase()))).filter(e=>status==='all'||(status==='low'?(e.working?e.present/e.working:0)<.8:(e.working?e.present/e.working:0)>=.8))
 const openEmployee=async person=>{setDetail({person,loading:true});try{const data=await attendanceApi.getMonthlyAttendance(year,month+1,person.id);setDetail({person,data})}catch(error){setDetail({person,error})}}
 const fyOptions=['FY 2026-27','FY 2027-28','FY 2028-29']
 const fyMonths=financialYearMonths(fy)
 return <section><div className="att-card att-team-filters"><label><span>Search Employees</span><div><Search size={16}/><input placeholder="Search by name…" value={query} onChange={e=>setQuery(e.target.value)}/></div></label><label>Employee<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">All Employees</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Financial Year<select value={fy} onChange={e=>{const first=financialYearMonths(e.target.value)[0];setYear(first.year);setMonth(first.month)}}>{fyOptions.map(value=><option key={value}>{value}</option>)}</select></label><label>Month<select value={`${year}-${month}`} onChange={e=>{const [nextYear,nextMonth]=e.target.value.split('-').map(Number);setYear(nextYear);setMonth(nextMonth)}}>{fyMonths.map(item=><option value={`${item.year}-${item.month}`} key={item.label}>{item.label}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All</option><option value="good">80%+</option><option value="low">Below 80%</option></select></label></div>{loading?<div className="att-empty"><p>Loading team attendance…</p></div>:rows.length?<div className="att-table-card"><table><thead><tr><th>Employee</th><th>Working</th><th>Present</th><th>Leave</th><th>Corrections</th><th>Unmarked</th><th>Total Hours</th><th>Leave Balance</th><th>Attendance %</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><button className="att-link" type="button" onClick={()=>openEmployee(e)}><div className="att-person"><i>{initials(e.name)}</i><span><b>{e.name}</b><small>{e.role}</small></span></div></button></td><td>{e.working}</td><td>{e.present}</td><td>{e.leave}</td><td>{e.corrections}</td><td>{e.unmarked}</td><td>{e.hours}</td><td>{e.balance} days</td><td><StatusPill status={`${e.working?Math.round(e.present/e.working*100):0}%`}/></td></tr>)}</tbody></table></div>:<div className="att-empty"><Users size={36}/><h3>No attendance data found.</h3><p>Employees will appear here when profile data is available.</p></div>}{detail&&<Modal title={`${detail.person.name} · Attendance`} subtitle={`${fy} · ${MONTHS[month]} ${year}`} onClose={()=>setDetail(null)} wide>{detail.loading?<div className="att-empty"><p>Loading calendar…</p></div>:detail.error?<div className="att-empty"><p>Unable to load this employee’s attendance.</p></div>:<AttendanceCalendar year={year} month={month} records={Object.fromEntries((detail.data?.records||[]).map(r=>[r.attendance_date,{status:statusLabel(r.status),in:time(r.clock_in_at),out:time(r.clock_out_at),duration:durationLabel(r.worked_minutes||0)}]))} holidays={(detail.data?.holidays||[]).map(h=>({date:h.holiday_date,name:h.holiday_name}))} onDay={()=>{}}/>}</Modal>}</section>
}

export { AttendancePermissionSettings }
