import { useEffect, useState } from 'react'
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Search, Users } from 'lucide-react'
import { useAuth } from '../context/useAuth'
import { useAdminAccess } from '../hooks/useAdminAccess'
import { AttendanceCalendar, CorrectionModal, DetailsModal, Modal, StatusPill, Toast, TodayAttendanceCard } from '../features/attendance/AttendanceComponents'
import { HOLIDAY_TYPES, MONTHS, calculateLeave, dateLabel, durationLabel, employees, initialCorrections, initialHolidays, initialLeaves, initials, iso, minutesBetween } from '../features/attendance/attendanceData'
import AttendancePermissionSettings from '../features/attendance/AttendancePermissionSettings'
import './AttendancePage.css'

const STORAGE='fb-attendance-ui-v1'
const now=new Date()
const seedRecords={
  '2026-07-01':{status:'Present',in:'09:28',out:'18:14',duration:'8h 46m'},'2026-07-02':{status:'Present',in:'09:35',out:'18:31',duration:'8h 56m'},'2026-07-03':{status:'Pending Correction',in:'09:42',out:null},'2026-07-06':{status:'Corrected',in:'09:30',out:'18:30',duration:'9h 00m'},'2026-07-07':{status:'Leave',duration:'Full Day'},'2026-07-08':{status:'Present',in:'09:31',out:'18:02',duration:'8h 31m'}
}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||{}}catch{return {}}}
function persist(value){localStorage.setItem(STORAGE,JSON.stringify(value))}

export default function AttendancePage(){
 const {user}=useAuth(); const {isAdmin,isSuperAdmin}=useAdminAccess({loadPermissions:false}); const [stored]=useState(()=>load())
 const [tab,setTab]=useState('attendance'),[month,setMonth]=useState(now.getMonth()),[year,setYear]=useState(now.getFullYear()),[clock,setClock]=useState(stored.clock||{}),[records,setRecords]=useState(stored.records||seedRecords),[corrections,setCorrections]=useState(stored.corrections||initialCorrections),[leaves,setLeaves]=useState(stored.leaves||initialLeaves),[holidays,setHolidays]=useState(stored.holidays||initialHolidays),[modal,setModal]=useState(null),[toast,setToast]=useState(null),[,setTick]=useState(0)
 const admin=isAdmin||isSuperAdmin; const displayName=user?.profile_name||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Team Member'
 useEffect(()=>{persist({clock,records,corrections,leaves,holidays})},[clock,records,corrections,leaves,holidays])
 useEffect(()=>{if(!clock.in||clock.out)return;const id=setInterval(()=>setTick(x=>x+1),30000);return()=>clearInterval(id)},[clock])
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),3000);return()=>clearTimeout(id)},[toast])
 const tell=(message,tone='success')=>setToast({message,tone})
 const todayKey=iso(now),todayHoliday=holidays.find(h=>h.date===todayKey),todayLeave=leaves.find(l=>l.employee==='Aarav Mehta'&&l.status==='Approved'&&todayKey>=l.start&&todayKey<=l.end),disabledReason=now.getDay()===0?'Weekly Off':todayHoliday?.name||todayLeave&&'Approved Leave'
 const monthRecords=Object.entries(records).filter(([key])=>{const d=new Date(`${key}T12:00:00`);return d.getMonth()===month&&d.getFullYear()===year})
 const working=new Date(year,month+1,0).getDate()-Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=>new Date(year,month,i+1)).filter(d=>d.getDay()===0).length
 const kpis=[['Working Days',working],['Present',monthRecords.filter(([,r])=>r.status==='Present'||r.status==='Corrected').length],['Leave',monthRecords.filter(([,r])=>r.status==='Leave').length],['Corrections',monthRecords.filter(([,r])=>r.status.includes('Correction')||r.status==='Corrected').length],['Unmarked',Math.max(0,Math.min(now.getDate()-1,working)-monthRecords.length)],['Holidays',holidays.filter(h=>new Date(`${h.date}T12:00:00`).getMonth()===month&&new Date(`${h.date}T12:00:00`).getFullYear()===year).length],['Total Hours',durationLabel(monthRecords.reduce((n,[,r])=>n+(r.in&&r.out?minutesBetween(r.in,r.out):0),0))]]
 const moveMonth=delta=>{const d=new Date(year,month+delta,1);setMonth(d.getMonth());setYear(d.getFullYear())}
 const monthControls=<div className="att-month-controls"><button onClick={()=>moveMonth(-1)} aria-label="Previous month"><ChevronLeft/></button><select value={month} onChange={e=>setMonth(+e.target.value)}>{MONTHS.map((m,i)=><option value={i} key={m}>{m}</option>)}</select><select value={year} onChange={e=>setYear(+e.target.value)}>{[2025,2026,2027].map(y=><option key={y}>{y}</option>)}</select><button onClick={()=>moveMonth(1)} aria-label="Next month"><ChevronRight/></button><button className="is-current" onClick={()=>{setMonth(now.getMonth());setYear(now.getFullYear())}}>Current month</button></div>
 const openCorrection=(key=todayKey,record=records[key])=>setModal({type:'correction',key,record})
 const submitCorrection=form=>{const d=new Date(`${form.date}T12:00:00`);if(!form.date||d>now||d.getDay()===0||holidays.some(h=>h.date===form.date)||!form.reason.trim()||minutesBetween(form.clockIn,form.clockOut)<=0){tell('Please check the date, times and mandatory reason.','error');return}if(corrections.some(c=>c.date===form.date&&c.status==='Pending Review')){tell('A pending correction already exists for this date.','error');return}setCorrections(c=>[{id:crypto.randomUUID(),employee:'Aarav Mehta',submitted:todayKey,date:form.date,clockIn:form.clockIn,clockOut:form.clockOut,duration:durationLabel(minutesBetween(form.clockIn,form.clockOut)),reason:form.reason,status:'Pending Review',reviewedBy:'—',reviewedOn:'—',note:'—'},...c]);setRecords(r=>({...r,[form.date]:{...r[form.date],status:'Pending Correction'}}));setModal(null);tell('Correction request submitted for approval.')}
 const onClock=()=>{if(disabledReason){tell(`Attendance is disabled: ${disabledReason}.`,'error');return}if(!clock.in){const value=new Date();setClock({in:value.toTimeString().slice(0,5),timestamp:value.getTime()});tell('Clocked in successfully.')}else if(!clock.out){const out=new Date().toTimeString().slice(0,5);setClock(c=>({...c,out}));setRecords(r=>({...r,[todayKey]:{status:'Present',in:clock.in,out,duration:durationLabel(minutesBetween(clock.in,out))}}));tell('Clocked out successfully.')}else tell('You have already clocked out today.','error')}
 const tabs=[['attendance','My Attendance',CalendarDays],['requests','My Requests',ClipboardList],...(admin?[['approvals','Approval Centre',CheckCircle2]]:[]),['holidays','Holiday Calendar',CalendarDays],...(admin?[['team','Team Attendance',Users]]:[])]
 return <div className="attendance-page"><Toast toast={toast}/><header className="att-page-head"><h1>Attendance &amp; Leave</h1><p>Track attendance, manage leave and review monthly attendance records.</p></header><nav className="att-tabs">{tabs.map(([key,label,Icon])=><button className={tab===key?'is-active':''} key={key} onClick={()=>setTab(key)}><Icon size={17}/>{label}{key==='approvals'&&<em>{corrections.filter(x=>x.status==='Pending Review').length+leaves.filter(x=>x.status==='Pending Review').length}</em>}</button>)}</nav>
 {tab==='attendance'&&<><TodayAttendanceCard today={now} clock={clock} onClock={onClock} onCorrection={()=>openCorrection()} onLeave={()=>setModal({type:'leave'})} disabledReason={disabledReason}/><div className="att-kpis">{kpis.map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><AttendanceCalendar year={year} month={month} records={records} holidays={holidays} onMonth={monthControls} onDay={cell=>setModal({type:'details',cell})}/></>}
 {tab==='requests'&&<Requests corrections={corrections.filter(x=>x.employee==='Aarav Mehta')} leaves={leaves.filter(x=>x.employee==='Aarav Mehta')} onCancel={(kind,id)=>{(kind==='correction'?setCorrections:setLeaves)(rows=>rows.map(x=>x.id===id?{...x,status:'Cancelled'}:x));tell('Request cancelled.')}}/>}
 {tab==='approvals'&&admin&&<Approvals corrections={corrections} leaves={leaves} onReview={(kind,item)=>setModal({type:'review',kind,item})}/>} {tab==='holidays'&&<Holidays admin={admin} year={year} setYear={setYear} holidays={holidays} onAdd={()=>setModal({type:'holiday'})} onDelete={id=>{setHolidays(h=>h.filter(x=>x.id!==id));tell('Holiday removed.')}}/>} {tab==='team'&&admin&&<Team year={year} month={month} setYear={setYear} setMonth={setMonth}/>} 
 {modal?.type==='correction'&&<CorrectionModal date={modal.key} existing={modal.record} onClose={()=>setModal(null)} onSubmit={submitCorrection}/>} {modal?.type==='details'&&<DetailsModal cell={modal.cell} onClose={()=>setModal(null)} onCorrection={()=>{const c=modal.cell;setModal({type:'correction',key:c.key,record:c.record})}} onLeave={()=>setModal({type:'leave',date:modal.cell.key})}/>} {modal?.type==='leave'&&<LeaveModal date={modal.date} holidays={holidays} onClose={()=>setModal(null)} onSubmit={item=>{setLeaves(x=>[item,...x]);setModal(null);tell('Leave request submitted for approval.')}}/>} {modal?.type==='review'&&<ReviewModal {...modal} onClose={()=>setModal(null)} onSubmit={(status,note)=>{const setter=modal.kind==='correction'?setCorrections:setLeaves;setter(rows=>rows.map(x=>x.id===modal.item.id?{...x,status,reviewedBy:displayName,reviewedOn:dateLabel(todayKey),note:note||'—'}:x));if(status==='Approved'&&modal.kind==='correction')setRecords(r=>({...r,[modal.item.date]:{status:'Corrected',in:modal.item.clockIn,out:modal.item.clockOut,duration:modal.item.duration}}));setModal(null);tell(`Request ${status.toLowerCase()}.`)}}/>} {modal?.type==='holiday'&&<HolidayForm holidays={holidays} onClose={()=>setModal(null)} onSubmit={h=>{setHolidays(x=>[h,...x]);setModal(null);tell('Holiday added.')}}/>}
 </div>
}

function Requests({corrections,leaves,onCancel}){const [sub,setSub]=useState('correction'),rows=sub==='correction'?corrections:leaves;return <section><SubTabs sub={sub} setSub={setSub}/><Table rows={rows} kind={sub} mine onCancel={onCancel}/></section>}
function Approvals({corrections,leaves,onReview}){const [sub,setSub]=useState('correction'),rows=(sub==='correction'?corrections:leaves).filter(x=>x.status==='Pending Review');return <section><SubTabs sub={sub} setSub={setSub} counts={[corrections.filter(x=>x.status==='Pending Review').length,leaves.filter(x=>x.status==='Pending Review').length]}/><Table rows={rows} kind={sub} onReview={onReview}/></section>}
function SubTabs({sub,setSub,counts}){return <div className="att-subtabs"><button className={sub==='correction'?'is-active':''} onClick={()=>setSub('correction')}>Attendance Corrections {counts&&<em>{counts[0]}</em>}</button><button className={sub==='leave'?'is-active':''} onClick={()=>setSub('leave')}>Leave Requests {counts&&<em>{counts[1]}</em>}</button></div>}
function Table({rows,kind,mine,onCancel,onReview}){if(!rows.length)return <div className="att-empty"><ClipboardList size={36}/><h3>No {kind==='correction'?'correction':'leave'} requests {mine?'yet':'to review'}.</h3><p>{mine?'New requests will appear here.':'You are all caught up.'}</p></div>;return <div className="att-table-card"><table><thead><tr>{!mine&&<th>Employee</th>}<th>Submitted On</th><th>{kind==='correction'?'Attendance Date':'Leave Period'}</th><th>{kind==='correction'?'Requested Times':'Type'}</th><th>{kind==='correction'?'Duration':'Charged Days'}</th><th>Reason</th><th>Status</th>{mine&&<><th>Reviewed By</th><th>Reviewed On</th><th>Review Note</th></>}<th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}>{!mine&&<td><b>{x.employee}</b></td>}<td>{dateLabel(x.submitted)}</td><td>{kind==='correction'?dateLabel(x.date):`${dateLabel(x.start)} – ${dateLabel(x.end)}`}</td><td>{kind==='correction'?`${x.clockIn} – ${x.clockOut}`:x.type}</td><td>{kind==='correction'?x.duration:x.charged}</td><td className="att-reason">{x.reason}</td><td><StatusPill status={x.status}/></td>{mine&&<><td>{x.reviewedBy}</td><td>{x.reviewedOn}</td><td>{x.note}</td></>}<td>{x.status==='Pending Review'&&(mine?<button className="att-link danger" onClick={()=>onCancel(kind,x.id)}>Cancel</button>:<button className="att-link" onClick={()=>onReview(kind,x)}>Review</button>)}</td></tr>)}</tbody></table></div>}

function LeaveModal({date='',holidays,onClose,onSubmit}){const [form,setForm]=useState({start:date,end:date,type:'Full Day',session:'First Half',reason:''}),calc=calculateLeave(form.start,form.end,form.type,holidays),balance=4.5,projected=balance-calc.charged,lop=Math.max(0,-projected);const submit=()=>{if(!form.start||!form.end||form.end<form.start||!form.reason.trim()){return}onSubmit({id:crypto.randomUUID(),employee:'Aarav Mehta',submitted:iso(new Date()),...form,type:form.type==='Half Day'?`${form.type} · ${form.session}`:form.type,charged:calc.charged,balance,projected,lop,reason:form.reason,status:'Pending Review',reviewedBy:'—',reviewedOn:'—',note:'—'})};return <Modal title="Apply Leave" subtitle="Plan time off and review the leave calculation before submitting." onClose={onClose} wide><div className="att-form"><div className="att-form-grid"><label>Start Date *<input type="date" value={form.start} onChange={e=>setForm({...form,start:e.target.value,end:form.end||e.target.value})}/></label><label>End Date *<input type="date" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label><label>Leave Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Full Day</option><option>Half Day</option></select></label>{form.type==='Half Day'&&<label>Half Day Session<select value={form.session} onChange={e=>setForm({...form,session:e.target.value})}><option>First Half</option><option>Second Half</option></select></label>}</div><div className="att-balance"><div><small>Current Leave Balance</small><b>{balance} days</b></div><div><small>Requested Leave Days</small><b>{calc.charged}</b></div><div><small>Projected Balance</small><b className={projected<0?'danger':''}>{projected}</b></div><div><small>Loss of Pay Days</small><b>{lop}</b></div></div><div className="att-breakdown"><h3>Leave calculation breakdown</h3>{calc.days.map(d=><div key={d.date}><span>{d.label}</span><span>{d.reason}</span><b>{d.charged}</b></div>)}</div>{projected<0&&<div className="att-warning"><b>Insufficient Paid Leave Balance</b><span>This request will reduce your paid leave balance below zero. The excess leave may be treated as Loss of Pay according to company policy.</span></div>}<label>Reason *<textarea rows="3" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div><footer><button className="att-secondary" onClick={onClose}>Go Back</button><button className="att-primary" onClick={submit}>{projected<0?'Continue and Submit':'Submit for Approval'}</button></footer></Modal>}
function ReviewModal({item,kind,onClose,onSubmit}){const [decision,setDecision]=useState('Approved'),[note,setNote]=useState('');return <Modal title="Review Request" subtitle={`${item.employee} · ${kind==='correction'?'Attendance correction':'Leave request'}`} onClose={onClose}><div className="att-review-summary"><StatusPill status={item.status}/><p>{item.reason}</p></div><div className="att-form"><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option>Approved</option><option>Rejected</option></select></label><label>{decision==='Rejected'?'Rejection reason *':'Approval note (optional)'}<textarea rows="4" value={note} onChange={e=>setNote(e.target.value)}/></label></div><footer><button className="att-secondary" onClick={onClose}>Cancel</button><button className="att-primary" disabled={decision==='Rejected'&&!note.trim()} onClick={()=>onSubmit(decision,note)}>{decision==='Approved'?'Approve Request':'Reject Request'}</button></footer></Modal>}
function Holidays({admin,year,setYear,holidays,onAdd,onDelete}){const list=holidays.filter(h=>new Date(`${h.date}T12:00:00`).getFullYear()===year).sort((a,b)=>a.date.localeCompare(b.date));return <section className="att-card att-holidays"><div className="att-section-head"><div><h2>Holiday Calendar</h2><p>Company holidays and optional days off.</p></div><div><select value={year} onChange={e=>setYear(+e.target.value)}><option>2025</option><option>2026</option><option>2027</option></select>{admin&&<button className="att-primary" onClick={onAdd}>+ Add Holiday</button>}</div></div><div className="att-holiday-grid">{list.map(h=><article key={h.id}><div className="att-holiday-date"><b>{new Date(`${h.date}T12:00:00`).getDate()}</b><span>{MONTHS[new Date(`${h.date}T12:00:00`).getMonth()].slice(0,3)}</span></div><div><h3>{h.name}</h3><p>{h.description}</p><StatusPill status={h.type}/></div>{admin&&<button className="att-link danger" onClick={()=>onDelete(h.id)}>Delete</button>}</article>)}</div></section>}
function HolidayForm({holidays,onClose,onSubmit}){const [form,setForm]=useState({name:'',date:'',type:HOLIDAY_TYPES[0],description:''});return <Modal title="Add Holiday" subtitle="Add a day to the company holiday calendar." onClose={onClose}><div className="att-form"><label>Holiday Name *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Date *<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{HOLIDAY_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button className="att-secondary" onClick={onClose}>Cancel</button><button className="att-primary" disabled={!form.name||!form.date||holidays.some(h=>h.date===form.date)} onClick={()=>onSubmit({...form,id:crypto.randomUUID()})}>Add Holiday</button></footer></Modal>}
function Team({year,month,setYear,setMonth}){const [query,setQuery]=useState(''),[employee,setEmployee]=useState('all'),[status,setStatus]=useState('all');const rows=employees.filter(e=>(employee==='all'||e.id===employee)&&(!query||e.name.toLowerCase().includes(query.toLowerCase()))).filter(e=>status==='all'||(status==='low'?e.present/e.working<.8:e.present/e.working>=.8));return <section><div className="att-card att-team-filters"><label><span>Search Employees</span><div><Search size={16}/><input placeholder="Search by name…" value={query} onChange={e=>setQuery(e.target.value)}/></div></label><label>Employee<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">All Employees</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Month<select value={month} onChange={e=>setMonth(+e.target.value)}>{MONTHS.map((m,i)=><option value={i} key={m}>{m}</option>)}</select></label><label>Year<select value={year} onChange={e=>setYear(+e.target.value)}><option>2026</option><option>2025</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All</option><option value="good">80%+</option><option value="low">Below 80%</option></select></label></div><div className="att-table-card"><table><thead><tr><th>Employee</th><th>Working</th><th>Present</th><th>Leave</th><th>Corrections</th><th>Unmarked</th><th>Total Hours</th><th>Attendance %</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><div className="att-person"><i>{initials(e.name)}</i><span><b>{e.name}</b><small>{e.role}</small></span></div></td><td>{e.working}</td><td>{e.present}</td><td>{e.leave}</td><td>{e.corrections}</td><td>{e.unmarked}</td><td>{e.hours}</td><td><StatusPill status={`${Math.round(e.present/e.working*100)}%`}/></td></tr>)}</tbody></table></div></section>}

export { AttendancePermissionSettings }
