const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../../..')
const read = relativePath => fs.readFileSync(path.join(root, relativePath), 'utf8')
const jobsPage = read('src/pages/JobsPage.jsx')
const publicRolesPage = read('src/pages/PublicRolesPage.jsx')
const publicRolesCss = read('src/pages/PublicRolesPage.css')
const appliedPage = read('src/pages/AppliedCandidatesPage.jsx')
const appliedCss = read('src/pages/AppliedCandidatesPage.css')
const sidebar = read('src/components/Sidebar.jsx')
const appliedRoutes = read('server/src/routes/appliedCandidates.js')
const publicRoutes = read('server/src/routes/publicRoles.js')

test('Mandate publication fields stay checkbox-gated and omit the slug control', () => {
  assert.match(jobsPage, /<strong>Publish this role<\/strong>/)
  assert.match(jobsPage, /\{Boolean\(form\.is_public\) && <>[\s\S]*Public Role Name/)
  assert.doesNotMatch(jobsPage, />Public Slug</)
  assert.match(jobsPage, /Public Skills[\s\S]{0,100}\(Optional\)/)
  assert.match(jobsPage, /mandate-public-toast/)
})

test('public page uses the brand header, multi-location filter, and optional application context fields', () => {
  assert.match(publicRolesPage, /fyndbridge-official-logo/)
  assert.match(publicRolesPage, />Back to Home<\/a>/)
  assert.match(publicRolesPage, /function LocationFilter/)
  assert.match(publicRolesPage, /aria-multiselectable="true"/)
  assert.doesNotMatch(publicRolesPage, /experienceFilter|setExperienceFilter/)
  assert.match(publicRolesPage, /label="LinkedIn" required=\{false\}/)
  assert.match(publicRolesPage, /label="Comments" required=\{false\}/)
  assert.match(publicRolesCss, /\.public-number-input::-webkit-inner-spin-button/)
  assert.doesNotMatch(publicRolesCss, /public-select-control/)
})

test('Applied Candidates uses body portals, optional context fields, simple rejection, and rectangular actions', () => {
  assert.ok((appliedPage.match(/createPortal\(/g) || []).length >= 2)
  assert.match(appliedPage, /document\.body/)
  assert.doesNotMatch(appliedPage, /Keep Pending|rejectionReason|setRejectionReason/)
  assert.match(appliedPage, /label="Expected CTC \(LPA\)" error=/)
  assert.match(appliedPage, /label="LinkedIn" error=/)
  assert.match(appliedPage, /label="Comments" full error=/)
  assert.match(appliedCss, /\.applied-content-overlay \{ position: fixed; inset: 0; z-index: 100000/)
  assert.match(appliedCss, /\.applied-convert-action \{ width: auto; min-width: 132px/)
  assert.match(appliedCss, /\.applied-candidates-table th \{[\s\S]*text-align: center/)
})

test('sidebar count badges are event-driven and Applied count remains behind page permission middleware', () => {
  assert.match(sidebar, /\/api\/public\/open-roles\/count/)
  assert.match(sidebar, /\/api\/applied-candidates\/count/)
  assert.match(sidebar, /ats:public-roles-updated/)
  assert.match(sidebar, /ats:applied-candidates-updated/)
  assert.doesNotMatch(sidebar, /setInterval|poll/i)
  assert.ok(appliedRoutes.indexOf("requirePageViewPermission('applied_candidates')") < appliedRoutes.indexOf("router.get('/count'"))
  assert.match(publicRoutes, /router\.get\('\/open-roles\/count', controller\.countOpenRoles\)/)
})
